### PR TITLE
docs: add Labbe-Mini to Keyboards

### PR DESCRIPTION
**Pull request by alabbe9545**

### CODE REVIEW

**Comment by alabbe9545** [comment]
Is there any problem with my changes?

**Comment by alabbe9545** [comment]
Hello @BenRoe is something needed from my side to be merged?

**Comment by BenRoe** [comment]
> Hello @BenRoe is something needed from my side to be merged?

Sry, had no time to check the PR. Will check it tomorrow.

**Comment by alabbe9545** [comment]
Thanks. 
in the recent commit i just fixed the keyboard description and position in the list

**Comment by BenRoe** [comment]
> Thanks.
> in the recent commit i just fixed the keyboard description and position in the list

Great.
The merge need some time. Netlify can't build the site. Have to investigate what the problem is.

**Pull request merged**
