### PR TITLE
Added Georgi, Gergo

### PR DESCRIPTION
**Pull request by germ**

### CODE REVIEW

**Comment by BenRoe** [comment]
Hello,
thank you for your contribution. Are these keyboards open source?

**Comment by germ** [comment]
Not yet, once production ends they will be. That being said the key placements/edges are provided and cases are open source. 

Mostly to prevent low effort cloning, similar to how bakingpy does it.

**Comment by BenRoe** [comment]
Ok, if the pbc are open source please comment here and i will merge it. Until i will close it.

**Comment by germ** [comment]
Ah, you should probably edit the README so others know that. No idea these were all open boards :)

**Pull request closed without merging**
