### PR TITLE
Add RGBKB Zen

### PR DESCRIPTION
**Pull request by kageurufu**
PCB and Plate files at https://github.com/RGBKB/Keyboard-files/tree/master/Zen

### CODE REVIEW

**Comment by BenRoe** [comment]
Can you ask the author of the zen image, if we can use it here?

**Comment by kageurufu** [comment]
Asked him on discord, otherwise I've got a few pictures of my Zen somewhere

**Comment by Legonut** [comment]
> Can you ask the author of the zen image, if we can use it here?

Yeah! Go ahead.

**Comment by BenRoe** [comment]
@Legonut is rgbkb.net your site? If yes the github link is brocken on https://www.rgbkb.net/pages/about-contact

BTW very interested in the Zygomorph keyboard. :scream:

**Comment by kageurufu** [comment]
Yep, @Legonut is the designer. You should join the discord, news will be posted in the updates channel!

**Pull request merged**
