### PR TITLE
docs: Add dumbpad

### PR DESCRIPTION
**Pull request by leon-anavi**
Add dumpad, a 4x4 macro/numpad with rotary encoder. Compatible
with QMK firmware.

Signed-off-by: Leon Anavi <leon@anavi.org>

### CODE REVIEW

**Comment by BenRoe** [comment]
Hi @leon-anavi,
thank you for your contribution. Can you capitalise "Dumpad" and add the tag "rotary encoder" to it.

**Comment by leon-anavi** [comment]
Sure, done. Cheers, Leon

**Comment by BenRoe** [comment]
There are no changes. I can see only the first commit.

**Comment by leon-anavi** [comment]
Sorry, I forgot to `git add` the modified file :) It should be OK now. Best regards, Leon

**Pull request merged**
