### PR TITLE
Add "Creating local development environment"

### PR DESCRIPTION
**Pull request by mateossh**
When someone clones repo and wants local environment, he has to deal with errors that aren't obvious to fix. If someone sees such informations in README, issues could be omitted

### CODE REVIEW

**Comment by BenRoe** [comment]
Never thought about that.
Thats a good idea. Thank you.
Will check if we create a env file for the github token var

**Comment by mateossh** [comment]
@BenRoe can you approve this PR so it counts towards my Hacktoberfest?

**Comment by BenRoe** [comment]
Please test if this is working without the github token. If yes, mark the section as optional.
It's only necessary to collect the contributor for the footer.

**Comment by mateossh** [comment]
Yes, both variables are required
Screenshot from 2021-10-31 13-52-35

**Pull request merged**
