### PR TITLE
docs/README.md: Add ANAVI Macro Pad 8

### PR DESCRIPTION
**Pull request by leon-anavi**
Include ANAVI Macro Pad 8 to the list of mechanical keyboards (in
alphabetical order).

Signed-off-by: Leon Anavi <leon@anavi.org>

### CODE REVIEW

**Comment by BenRoe** [comment]
@leon-anavi thanks for the contribution. please move it to the numpad/macropad section.
I can't find files for the case in the repo. please add some, or remove the case entry.

**Comment by leon-anavi** [comment]
Hi @BenRoe,

Thank you for the quick feedback. I will move it to the numpad/macropad section. 

The acrylic enclosure is available in a separate repo: https://github.com/AnaviTechnology/anavi-cases/tree/master/anavi-macro-pad-8-case A link to it is available in the README of https://github.com/AnaviTechnology/anavi-macro-pad-8

Best regards,
Leon

**Comment by leon-anavi** [comment]
Hi @BenRoe,

I've updated the patch. I added links to the appropriate repositories for the pcb and the stl under "Available Files". Is this OK?

Thanks,
Leon

**Comment by BenRoe** [comment]
Hi, sorry for bothering again. Please remove the links from the pcb, and case tag and write all tags lower case (kicad,...).
Then we have it.

**Comment by leon-anavi** [comment]
Hi,

Done. Thanks for the feedback. Let me know if any other changes are required.

Thanks, Leon

**Pull request merged**
